// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: pkg/grpc/protobuf/digimon.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PrimaryNode_ReceiveEncryptedMessage_FullMethodName = "/digimon.PrimaryNode/ReceiveEncryptedMessage"
)

// PrimaryNodeClient is the client API for PrimaryNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrimaryNodeClient interface {
	// Recibe un mensaje encriptado desde el cliente regional
	ReceiveEncryptedMessage(ctx context.Context, in *EncryptedMessage, opts ...grpc.CallOption) (*Empty, error)
}

type primaryNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewPrimaryNodeClient(cc grpc.ClientConnInterface) PrimaryNodeClient {
	return &primaryNodeClient{cc}
}

func (c *primaryNodeClient) ReceiveEncryptedMessage(ctx context.Context, in *EncryptedMessage, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PrimaryNode_ReceiveEncryptedMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrimaryNodeServer is the server API for PrimaryNode service.
// All implementations must embed UnimplementedPrimaryNodeServer
// for forward compatibility.
type PrimaryNodeServer interface {
	// Recibe un mensaje encriptado desde el cliente regional
	ReceiveEncryptedMessage(context.Context, *EncryptedMessage) (*Empty, error)
	mustEmbedUnimplementedPrimaryNodeServer()
}

// UnimplementedPrimaryNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrimaryNodeServer struct{}

func (UnimplementedPrimaryNodeServer) ReceiveEncryptedMessage(context.Context, *EncryptedMessage) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveEncryptedMessage not implemented")
}
func (UnimplementedPrimaryNodeServer) mustEmbedUnimplementedPrimaryNodeServer() {}
func (UnimplementedPrimaryNodeServer) testEmbeddedByValue()                     {}

// UnsafePrimaryNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrimaryNodeServer will
// result in compilation errors.
type UnsafePrimaryNodeServer interface {
	mustEmbedUnimplementedPrimaryNodeServer()
}

func RegisterPrimaryNodeServer(s grpc.ServiceRegistrar, srv PrimaryNodeServer) {
	// If the following call pancis, it indicates UnimplementedPrimaryNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PrimaryNode_ServiceDesc, srv)
}

func _PrimaryNode_ReceiveEncryptedMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptedMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrimaryNodeServer).ReceiveEncryptedMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrimaryNode_ReceiveEncryptedMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrimaryNodeServer).ReceiveEncryptedMessage(ctx, req.(*EncryptedMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// PrimaryNode_ServiceDesc is the grpc.ServiceDesc for PrimaryNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrimaryNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "digimon.PrimaryNode",
	HandlerType: (*PrimaryNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveEncryptedMessage",
			Handler:    _PrimaryNode_ReceiveEncryptedMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc/protobuf/digimon.proto",
}
