// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.21.12
// source: pkg/grpc/protobuf/digimon.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensajes comunes
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protobuf_digimon_proto_rawDescGZIP(), []int{0}
}

type EncryptedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EncryptedData string `protobuf:"bytes,1,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
}

func (x *EncryptedMessage) Reset() {
	*x = EncryptedMessage{}
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedMessage) ProtoMessage() {}

func (x *EncryptedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedMessage.ProtoReflect.Descriptor instead.
func (*EncryptedMessage) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protobuf_digimon_proto_rawDescGZIP(), []int{1}
}

func (x *EncryptedMessage) GetEncryptedData() string {
	if x != nil {
		return x.EncryptedData
	}
	return ""
}

type TerminateProcess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *TerminateProcess) Reset() {
	*x = TerminateProcess{}
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateProcess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateProcess) ProtoMessage() {}

func (x *TerminateProcess) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateProcess.ProtoReflect.Descriptor instead.
func (*TerminateProcess) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protobuf_digimon_proto_rawDescGZIP(), []int{2}
}

func (x *TerminateProcess) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type TerminateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TerminateResponse) Reset() {
	*x = TerminateResponse{}
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateResponse) ProtoMessage() {}

func (x *TerminateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateResponse.ProtoReflect.Descriptor instead.
func (*TerminateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protobuf_digimon_proto_rawDescGZIP(), []int{3}
}

func (x *TerminateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TaiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TaiRequest) Reset() {
	*x = TaiRequest{}
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaiRequest) ProtoMessage() {}

func (x *TaiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaiRequest.ProtoReflect.Descriptor instead.
func (*TaiRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protobuf_digimon_proto_rawDescGZIP(), []int{4}
}

func (x *TaiRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AttackDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataCollected int32 `protobuf:"varint,1,opt,name=data_collected,json=dataCollected,proto3" json:"data_collected,omitempty"`
}

func (x *AttackDataResponse) Reset() {
	*x = AttackDataResponse{}
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackDataResponse) ProtoMessage() {}

func (x *AttackDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackDataResponse.ProtoReflect.Descriptor instead.
func (*AttackDataResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protobuf_digimon_proto_rawDescGZIP(), []int{5}
}

func (x *AttackDataResponse) GetDataCollected() int32 {
	if x != nil {
		return x.DataCollected
	}
	return 0
}

type DigimonInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Attribute string `protobuf:"bytes,2,opt,name=attribute,proto3" json:"attribute,omitempty"`
}

func (x *DigimonInfo) Reset() {
	*x = DigimonInfo{}
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigimonInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigimonInfo) ProtoMessage() {}

func (x *DigimonInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigimonInfo.ProtoReflect.Descriptor instead.
func (*DigimonInfo) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protobuf_digimon_proto_rawDescGZIP(), []int{6}
}

func (x *DigimonInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DigimonInfo) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

type StoreDigimonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StoreDigimonResponse) Reset() {
	*x = StoreDigimonResponse{}
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreDigimonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreDigimonResponse) ProtoMessage() {}

func (x *StoreDigimonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreDigimonResponse.ProtoReflect.Descriptor instead.
func (*StoreDigimonResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protobuf_digimon_proto_rawDescGZIP(), []int{7}
}

func (x *StoreDigimonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DigimonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DigimonRequest) Reset() {
	*x = DigimonRequest{}
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigimonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigimonRequest) ProtoMessage() {}

func (x *DigimonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigimonRequest.ProtoReflect.Descriptor instead.
func (*DigimonRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protobuf_digimon_proto_rawDescGZIP(), []int{8}
}

func (x *DigimonRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DigimonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attribute string `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
}

func (x *DigimonResponse) Reset() {
	*x = DigimonResponse{}
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigimonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigimonResponse) ProtoMessage() {}

func (x *DigimonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigimonResponse.ProtoReflect.Descriptor instead.
func (*DigimonResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protobuf_digimon_proto_rawDescGZIP(), []int{9}
}

func (x *DigimonResponse) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

type TerminateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TerminateRequest) Reset() {
	*x = TerminateRequest{}
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateRequest) ProtoMessage() {}

func (x *TerminateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateRequest.ProtoReflect.Descriptor instead.
func (*TerminateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protobuf_digimon_proto_rawDescGZIP(), []int{10}
}

func (x *TerminateRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protobuf_digimon_proto_rawDescGZIP(), []int{11}
}

func (x *StartResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AttackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttackValue int32 `protobuf:"varint,1,opt,name=attack_value,json=attackValue,proto3" json:"attack_value,omitempty"`
}

func (x *AttackRequest) Reset() {
	*x = AttackRequest{}
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackRequest) ProtoMessage() {}

func (x *AttackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackRequest.ProtoReflect.Descriptor instead.
func (*AttackRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protobuf_digimon_proto_rawDescGZIP(), []int{12}
}

func (x *AttackRequest) GetAttackValue() int32 {
	if x != nil {
		return x.AttackValue
	}
	return 0
}

type AttackResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *AttackResponse) Reset() {
	*x = AttackResponse{}
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackResponse) ProtoMessage() {}

func (x *AttackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protobuf_digimon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackResponse.ProtoReflect.Descriptor instead.
func (*AttackResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protobuf_digimon_proto_rawDescGZIP(), []int{13}
}

func (x *AttackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pkg_grpc_protobuf_digimon_proto protoreflect.FileDescriptor

var file_pkg_grpc_protobuf_digimon_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x64, 0x69, 0x67, 0x69, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x64, 0x69, 0x67, 0x69, 0x6d, 0x6f, 0x6e, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x39, 0x0a, 0x10, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x6e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x65, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x22, 0x2a,
	0x0a, 0x10, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x2d, 0x0a, 0x11, 0x54, 0x65,
	0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x26, 0x0a, 0x0a, 0x54, 0x61, 0x69,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x3b, 0x0a, 0x12, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x5f,
	0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0d, 0x64, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x22, 0x3b,
	0x0a, 0x0b, 0x44, 0x69, 0x67, 0x69, 0x6d, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x22, 0x30, 0x0a, 0x14, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x44, 0x69, 0x67, 0x69, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x20, 0x0a,
	0x0e, 0x44, 0x69, 0x67, 0x69, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x2f, 0x0a, 0x0f, 0x44, 0x69, 0x67, 0x69, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x22, 0x2c, 0x0a, 0x10, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x29,
	0x0a, 0x0d, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x32, 0x0a, 0x0d, 0x41, 0x74, 0x74,
	0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x74,
	0x74, 0x61, 0x63, 0x6b, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2a, 0x0a,
	0x0e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0xed, 0x01, 0x0a, 0x12, 0x50, 0x72,
	0x69, 0x6d, 0x61, 0x72, 0x79, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x44, 0x0a, 0x17, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x45, 0x6e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x19, 0x2e, 0x64, 0x69,
	0x67, 0x69, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0e, 0x2e, 0x64, 0x69, 0x67, 0x69, 0x6d, 0x6f, 0x6e,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x41, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x74, 0x74,
	0x61, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x13, 0x2e, 0x64, 0x69, 0x67, 0x69, 0x6d, 0x6f,
	0x6e, 0x2e, 0x54, 0x61, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x64,
	0x69, 0x67, 0x69, 0x6d, 0x6f, 0x6e, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x15, 0x53, 0x65, 0x6e,
	0x64, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x67, 0x6e,
	0x61, 0x6c, 0x12, 0x19, 0x2e, 0x64, 0x69, 0x67, 0x69, 0x6d, 0x6f, 0x6e, 0x2e, 0x54, 0x65, 0x72,
	0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x1a, 0x1a, 0x2e,
	0x64, 0x69, 0x67, 0x69, 0x6d, 0x6f, 0x6e, 0x2e, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xe4, 0x01, 0x0a, 0x0f, 0x44, 0x61,
	0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a,
	0x0c, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x44, 0x69, 0x67, 0x69, 0x6d, 0x6f, 0x6e, 0x12, 0x14, 0x2e,
	0x64, 0x69, 0x67, 0x69, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x69, 0x67, 0x69, 0x6d, 0x6f, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x1a, 0x1d, 0x2e, 0x64, 0x69, 0x67, 0x69, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x44, 0x69, 0x67, 0x69, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x48, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x44, 0x69, 0x67, 0x69, 0x6d, 0x6f, 0x6e,
	0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x64, 0x69, 0x67, 0x69,
	0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x69, 0x67, 0x69, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x64, 0x69, 0x67, 0x69, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x69, 0x67,
	0x69, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x09,
	0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x64, 0x69, 0x67, 0x69,
	0x6d, 0x6f, 0x6e, 0x2e, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x64, 0x69, 0x67, 0x69, 0x6d, 0x6f, 0x6e, 0x2e, 0x54,
	0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x32, 0x93, 0x01, 0x0a, 0x11, 0x44, 0x69, 0x61, 0x62, 0x6f, 0x72, 0x6f, 0x6d, 0x6f, 0x6e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x72, 0x74, 0x44,
	0x69, 0x61, 0x62, 0x6f, 0x72, 0x6f, 0x6d, 0x6f, 0x6e, 0x12, 0x0e, 0x2e, 0x64, 0x69, 0x67, 0x69,
	0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x64, 0x69, 0x67, 0x69,
	0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x43, 0x0a, 0x10, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x44, 0x69, 0x61, 0x62, 0x6f,
	0x72, 0x6f, 0x6d, 0x6f, 0x6e, 0x12, 0x16, 0x2e, 0x64, 0x69, 0x67, 0x69, 0x6d, 0x6f, 0x6e, 0x2e,
	0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x64, 0x69, 0x67, 0x69, 0x6d, 0x6f, 0x6e, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x49, 0x0a, 0x0a, 0x54, 0x61, 0x69, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x10, 0x44, 0x69, 0x61, 0x62, 0x6f, 0x72, 0x6f, 0x6d,
	0x6f, 0x6e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x12, 0x0e, 0x2e, 0x64, 0x69, 0x67, 0x69, 0x6d,
	0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e, 0x64, 0x69, 0x67, 0x69, 0x6d,
	0x6f, 0x6e, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x29, 0x5a, 0x27, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x6e, 0x6f, 0x64,
	0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_grpc_protobuf_digimon_proto_rawDescOnce sync.Once
	file_pkg_grpc_protobuf_digimon_proto_rawDescData = file_pkg_grpc_protobuf_digimon_proto_rawDesc
)

func file_pkg_grpc_protobuf_digimon_proto_rawDescGZIP() []byte {
	file_pkg_grpc_protobuf_digimon_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_protobuf_digimon_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_grpc_protobuf_digimon_proto_rawDescData)
	})
	return file_pkg_grpc_protobuf_digimon_proto_rawDescData
}

var file_pkg_grpc_protobuf_digimon_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pkg_grpc_protobuf_digimon_proto_goTypes = []any{
	(*Empty)(nil),                // 0: digimon.Empty
	(*EncryptedMessage)(nil),     // 1: digimon.EncryptedMessage
	(*TerminateProcess)(nil),     // 2: digimon.TerminateProcess
	(*TerminateResponse)(nil),    // 3: digimon.TerminateResponse
	(*TaiRequest)(nil),           // 4: digimon.TaiRequest
	(*AttackDataResponse)(nil),   // 5: digimon.AttackDataResponse
	(*DigimonInfo)(nil),          // 6: digimon.DigimonInfo
	(*StoreDigimonResponse)(nil), // 7: digimon.StoreDigimonResponse
	(*DigimonRequest)(nil),       // 8: digimon.DigimonRequest
	(*DigimonResponse)(nil),      // 9: digimon.DigimonResponse
	(*TerminateRequest)(nil),     // 10: digimon.TerminateRequest
	(*StartResponse)(nil),        // 11: digimon.StartResponse
	(*AttackRequest)(nil),        // 12: digimon.AttackRequest
	(*AttackResponse)(nil),       // 13: digimon.AttackResponse
}
var file_pkg_grpc_protobuf_digimon_proto_depIdxs = []int32{
	1,  // 0: digimon.PrimaryNodeService.ReceiveEncryptedMessage:input_type -> digimon.EncryptedMessage
	4,  // 1: digimon.PrimaryNodeService.GetAttackData:input_type -> digimon.TaiRequest
	2,  // 2: digimon.PrimaryNodeService.SendTerminationSignal:input_type -> digimon.TerminateProcess
	6,  // 3: digimon.DataNodeService.StoreDigimon:input_type -> digimon.DigimonInfo
	8,  // 4: digimon.DataNodeService.GetDigimonAttribute:input_type -> digimon.DigimonRequest
	10, // 5: digimon.DataNodeService.Terminate:input_type -> digimon.TerminateRequest
	0,  // 6: digimon.DiaboromonService.StartDiaboromon:input_type -> digimon.Empty
	12, // 7: digimon.DiaboromonService.AttackDiaboromon:input_type -> digimon.AttackRequest
	0,  // 8: digimon.TaiService.DiaboromonAttack:input_type -> digimon.Empty
	0,  // 9: digimon.PrimaryNodeService.ReceiveEncryptedMessage:output_type -> digimon.Empty
	5,  // 10: digimon.PrimaryNodeService.GetAttackData:output_type -> digimon.AttackDataResponse
	3,  // 11: digimon.PrimaryNodeService.SendTerminationSignal:output_type -> digimon.TerminateResponse
	7,  // 12: digimon.DataNodeService.StoreDigimon:output_type -> digimon.StoreDigimonResponse
	9,  // 13: digimon.DataNodeService.GetDigimonAttribute:output_type -> digimon.DigimonResponse
	3,  // 14: digimon.DataNodeService.Terminate:output_type -> digimon.TerminateResponse
	11, // 15: digimon.DiaboromonService.StartDiaboromon:output_type -> digimon.StartResponse
	13, // 16: digimon.DiaboromonService.AttackDiaboromon:output_type -> digimon.AttackResponse
	13, // 17: digimon.TaiService.DiaboromonAttack:output_type -> digimon.AttackResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_grpc_protobuf_digimon_proto_init() }
func file_pkg_grpc_protobuf_digimon_proto_init() {
	if File_pkg_grpc_protobuf_digimon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_grpc_protobuf_digimon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_pkg_grpc_protobuf_digimon_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_protobuf_digimon_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_protobuf_digimon_proto_msgTypes,
	}.Build()
	File_pkg_grpc_protobuf_digimon_proto = out.File
	file_pkg_grpc_protobuf_digimon_proto_rawDesc = nil
	file_pkg_grpc_protobuf_digimon_proto_goTypes = nil
	file_pkg_grpc_protobuf_digimon_proto_depIdxs = nil
}
