docker-logistica:
	sudo docker-compose down
	sudo docker-compose up --build konzu

docker-financiero:
	sudo docker-compose down
	sudo docker-compose up --build raquis

docker-cliente:
	sudo docker-compose down
	sudo docker-compose up --build clientes

docker-caravanas:
	sudo docker-compose down
	sudo docker-compose up --build caravanas