docker-pn:
	sudo docker-compose down
	sudo docker-compose up --build primary-node

docker-dn1:
	sudo docker-compose down
	sudo docker-compose up --build data-node-1

docker-dn2:
	sudo docker-compose down
	sudo docker-compose up --build data-node-2

docker-diaboromon:
	sudo docker-compose down
	sudo docker-compose up --build diaboromon

docker-tai:
	sudo docker-compose down
	sudo docker-compose up --build tai

docker-if:
	sudo docker-compose down
	sudo docker-compose up --build isla-file

docker-cf:
	sudo docker-compose down
	sudo docker-compose up --build continente-folder

docker-cs:
	sudo docker-compose down
	sudo docker-compose up --build continente-server